version: '3.7'

services:
  frontend:
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '/app/public/bible'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
